### ISSUE TITLE
multiprocessing in class methods

### ISSUE THREAD

**Issue by mistycheney** [mistycheney/MouseBrainAtlas#1]
I tried to refactor the code, so that there are FeatureExtractor class and ModelDetector class. However calling joblib Parallel functions within class methods causes "can't pickle instancemethod".

**possible solution**: use new serialization method, such as dill, which is implemented within pathos
reference: http://stackoverflow.com/questions/19984152/what-can-multiprocessing-and-dill-do-together

joblib is not yet using dill, although it is on their todo list (https://github.com/joblib/joblib/search?q=dill&ref=cmdform&type=Issues). So I tried to use pathos.multiprocessing directly, 
`from pathos.multiprocessing import ProcessingPool as Pool`

**Installation of pathos**: official website is http://trac.mystic.cacr.caltech.edu/project/pathos, but that release is very stale. Instead, use the development version https://github.com/uqfoundation/pathos and follow the instructions in the repo

This manages to do feature computation perfectly, but degrades to using only 2 or 3 processes at texton computation. I have no idea why.

**checkin**: `test_feature_extraction_pathos_failed.py`

**Comment by mmckerns** [comment]
You might try `multiprocess`, which has been decoupled from `pathos`… and is a very minimal `dill`-active fork of `multiprocessing`.  No idea why you are seeing `pathos` only compute on a single process… have you tried recent versions from github (of better, using `multiprocess`)?

**Comment by mistycheney** [comment]
Thanks, `multiprocess` works to some degree. However I am still unable to fully use parallelism in my case. The issue can be demonstrated by the following code.

I have a class that contains a **large** member variable.

```python
class A(object):
  def __init__(self):
    self.x = numpy.random.random((1e6,)) # some really large array
  def func(self): # a function that is expected to run concurrently
    # some computation that uses self.x
    return 0 # here I just return 0 for simplicity
```

I call the class this way:

```python
from multiprocess import Pool

a = A()
pool = Pool(16)
results = pool.map(a.func, range(16))
```

It is very slow. I suspect it is because the large array is copied to every process, instead of being shared. My question is, how can I share the large class member variable between the processes?

**Comment by mistycheney** [comment]
Move large data out of class and access them as module-level global variables from class methods - this combined with `multiprocess.Pool` achieves the desired parallelism.
